FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/
ENV DATABASE_URL="postgresql://user:pass@localhost:5432/db?schema=public"
RUN npm install
RUN npx prisma generate

EXPOSE 3000

CMD ["npm", "run", "dev"]
