FROM node:20

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY prisma ./prisma/
RUN npx prisma generate

COPY . .

EXPOSE 3000

# Use dotenv to load .env file
CMD ["sh", "-c", "npx dotenv -e .env -- npm run dev"]
